{% set name = "r5py" %}
{% set version = "1.0.4" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: fa3e5ac3e490a03eb36eafab0a7de41e54c18cb9cbbb1650424b8737891be239
  patches:
    - precision-of-comparison.patch

build:
  noarch: python
  script: python -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - openjdk >=21
    - ConfigArgParse
    - filelock
    - geohexgrid
    - geopandas
    - joblib
    - jpype1
    - numpy
    - pandas >=2.1.0
    - psutil
    - pyproj
    - requests
    - scikit-learn
    - shapely >=2.0
    - simplification
    - typing-extensions

test:
  requires:
    - python {{ python_min }}
    - pip
    - pyarrow
    - pytest
    - pytest-cov
    - pytest-lazy-fixtures
    - r5py.sampledata.helsinki
    - r5py.sampledata.sao_paulo
  source_files:
    - tests
  commands:
    - pip check
    - python -m pytest
  downstreams:
    - r5py.sampledata.helsinki
    - r5py.sampledata.sao_paulo

about:
  home: https://github.com/r5py/r5py
  summary: "Python wrapper for the R5 routing analysis engine"
  description: |
    R5py is a Python wrapper for the R5 routing analysis engine. It’s inspired
    by r5r, a wrapper for R, and is designed to interact with GeoPandas data
    frames.  Similar to r5r, r5py represents a simple way to run R5 locally. It
    allows users to generate detailed routing analyses or calculate travel time
    matrices using parallel computing, and integrates seamlessly with
    Python/Geopandas workflows.
  license: GPL-3.0-or-later OR MIT
  license_file:
    - LICENSE
    - licenses/
  doc_url: https://r5py.readthedocs.io/
  dev_url: https://github.com/r5py/r5py

extra:
  recipe-maintainers:
    - HTenkanen
    - christophfink
